await transporter.sendMail({
  from: `"GestoriaCitaIA" <${process.env.GMAIL_USER}>`,
  to: email,
  subject: "✅ Welcome to Malta Jobs",

  html: `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body style="margin:0;padding:0;background:#f5f7fb;font-family:Arial,Helvetica,sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f7fb;padding:40px 0;">

<tr>
<td align="center">

<table width="650" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 10px 30px rgba(0,0,0,.08);">

<tr>
<td style="background:#0B57D0;padding:40px;text-align:center;">

<h1 style="margin:0;color:#fff;font-size:34px;">
GestoriaCitaIA
</h1>

<p style="margin-top:10px;color:#fff;font-size:18px;">
Malta Jobs Platform
</p>

</td>
</tr>

<tr>
<td style="padding:45px;">

<h2 style="margin-top:0;">
Hello ${name},
</h2>

<p>
Thank you for choosing <strong>GestoriaCitaIA Malta Jobs</strong>.
</p>

<p>
We have successfully received your payment and your application has entered our recruitment system.
</p>

<p>
Our AI will now begin preparing your professional documents before applying to companies across Malta.
</p>

<h3>What happens next?</h3>

<ul style="line-height:30px;">
<li>✅ Professional CV generated by AI</li>
<li>✅ Professional Cover Letter generated by AI</li>
<li>✅ Your profile will be prepared</li>
<li>✅ Companies in Malta will start receiving your application</li>
</ul>

<p>
<b>Your Plan:</b> ${plan}
</p>

<div style="text-align:center;margin:40px 0;">

<a href="https://gestoriacitaia.com"
style="
background:#0B57D0;
color:#ffffff;
text-decoration:none;
padding:16px 35px;
border-radius:8px;
font-size:18px;
font-weight:bold;
display:inline-block;
">
Visit GestoriaCitaIA
</a>

</div>

<hr style="border:none;border-top:1px solid #eee;">

<p style="font-size:15px;color:#666;">
You will automatically receive another email as soon as your CV and Cover Letter are ready.
</p>

<p style="font-size:15px;color:#666;">
After that, we will begin submitting your application to employers that match your profile.
</p>

<p style="margin-top:40px;">
Kind regards,
</p>

<p>
<b>GestoriaCitaIA Recruitment Team</b>
</p>

</td>
</tr>

<tr>
<td style="background:#f8f8f8;padding:25px;text-align:center;font-size:13px;color:#777;">

© ${new Date().getFullYear()} GestoriaCitaIA

<br><br>

https://gestoriacitaia.com

</td>
</tr>

</table>

</td>
</tr>

</table>

</body>
</html>
`
});
