import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  ReactNode,
} from "react";

export type Lang = "es" | "en" | "darija";

type TranslationMap = Record<string, string>;
type AllTranslations = Record<Lang, TranslationMap>;

type LanguageContextType = {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  isRTL: boolean;
  translations: TranslationMap;
};

const STORAGE_KEY = "gestoriacitaia_lang";

const translations: AllTranslations = {
  es: {
    // NAVBAR
    nav_inicio: "Inicio",
    nav_panel: "Panel",
    nav_citas: "Citas",
    nav_reg: "Regularización 2026",
    nav_login: "Iniciar sesión",
    nav_logout: "Cerrar sesión",
    nav_documentos: "Documentos",
    nav_contacto: "Contacto",
    nav_idioma: "Idioma",

    // HERO
    hero_badge: "Agente IA de Extranjería — 100% legal y seguro",
    hero_title_1: "Descubre si puedes",
    hero_title_2: "regularizarte en España",
    hero_sub:
      "Nuestro agente IA analiza tu situación, revisa tus documentos y te guía paso a paso de forma clara, rápida y segura.",
    hero_btn1: "Empezar ahora",
    hero_btn_citas: "Buscar citas",
    hero_btn2: "Ver mi panel",
    hero_trust: "Miles de personas ya usan GestoriaCitaIA",

    // FEATURES HOME
    feat1: "Análisis rápido",
    feat2: "Revisión de documentos",
    feat3: "Preparación en PDF",
    feat4: "Asistencia paso a paso",

    // AGENTS
    agent_mo_role: "Especialista en Extranjería",
    agent_sara_role: "Buscar Citas · 24/7",

    // VIDEO
    landing_video_text: "Cómo funciona GestoriaCitaIA en 2 minutos",

    // PLANS
    plans_title: "Nuestros planes",
    plans_sub: "Elige la opción que mejor se adapta a tu situación",
    plan_popular: "Más popular",
    plan_btn: "Empezar",
    plan_free_btn: "Probar gratis",

    plan_free_name: "Gratis",
    plan_cita_name: "Plan Citas",
    plan_reg_name: "Plan Regularización",
    plan_std_name: "Plan Estándar",

    plan_free_f1: "Consulta inicial con agente IA",
    plan_free_f2: "Orientación básica del trámite",
    plan_free_f3: "Información general",
    plan_free_f4: "Acceso limitado",

    plan_cita_f1: "Búsqueda de citas",
    plan_cita_f2: "Seguimiento de disponibilidad",
    plan_cita_f3: "Avisos prioritarios",
    plan_cita_f4: "Asistente 24/7",
    plan_cita_f5: "Ayuda paso a paso",
    plan_cita_f6: "Soporte de gestión",

    plan_reg_f1: "Análisis de regularización",
    plan_reg_f2: "Revisión de documentos",
    plan_reg_f3: "Comprobación de requisitos",
    plan_reg_f4: "Preparación de expediente",
    plan_reg_f5: "Asistencia personalizada",

    plan_std_f1: "Todo lo del plan Citas",
    plan_std_f2: "Todo lo del plan Regularización",
    plan_std_f3: "Subida y revisión de documentos",
    plan_std_f4: "Preparación de formularios",
    plan_std_f5: "Seguimiento del expediente",
    plan_std_f6: "Notificaciones importantes",
    plan_std_f7: "Soporte completo",

    // TRÁMITES HOME
    tramites_title: "Trámites disponibles",
    tramites_sub: "Te ayudamos en los trámites más importantes de extranjería",
    tr_tie: "Renovación TIE",
    tr_visado_nac: "Visado nacional",
    tr_nie: "NIE",
    tr_empadron: "Empadronamiento",
    tr_trabajo: "Permiso de trabajo",
    tr_familiar: "Reagrupación familiar",
    tr_estudiante: "Estancia por estudios",
    tr_arraigo: "Arraigo",
    tr_conducir: "Canje de conducir",
    tr_larga: "Larga duración",
    tr_regreso: "Autorización de regreso",
    tr_ue: "Certificado UE",

    // COMMON
    common_loading: "Cargando...",
    common_error: "Ha ocurrido un error",
    common_success: "Operación realizada correctamente",
    common_cancel: "Cancelar",
    common_save: "Guardar",
    common_close: "Cerrar",
    common_continue: "Continuar",
    common_back: "Atrás",
    common_next: "Siguiente",
    common_send: "Enviar",
    common_yes: "Sí",
    common_no: "No",
    common_required: "Obligatorio",
    common_optional: "Opcional",
    common_select: "Seleccionar",
    common_search: "Buscar",
    common_download: "Descargar",
    common_upload: "Subir",
    common_delete: "Eliminar",
    common_edit: "Editar",
    common_view: "Ver",
    common_free: "Gratis",
    common_paid: "De pago",

    // PANEL
    panel_title: "Tu panel",
    panel_subtitle: "Gestiona tu proceso desde un solo lugar",
    panel_welcome: "Bienvenido",
    panel_cases: "Tus trámites",
    panel_documents: "Tus documentos",
    panel_notifications: "Notificaciones",
    panel_profile: "Perfil",
    panel_no_data: "Aún no hay datos disponibles",
    panel_header: "Panel",
    panel_tab_docs: "Documentos",
    panel_tab_profile: "Perfil",
    panel_tab_notifications: "Notificaciones",
    panel_plan_active: "Plan activo",
    panel_tab_resumen: "Resumen",
    panel_tab_tramites: "Trámites",
    panel_tab_citas: "Citas",
    panel_active: "Activo",
    panel_plan_used: "Plan usado",
    panel_procedures: "Trámites",
    panel_next_invoice: "Próxima factura",
    panel_manage_plan: "Gestionar plan",
    panel_new_appt: "Nueva cita",
    panel_tramites_curso: "Trámites en curso",
    panel_quick_actions: "Acciones rápidas",
    panel_referral_title: "Invita y gana",
    panel_referral_reward: "Descuento",
    panel_referral_desc: "Comparte tu código y consigue recompensas.",
    panel_referrals_bought: "Referidos completados",
    panel_referral_left: "Te faltan",
    panel_referral_more: "más para conseguir tu recompensa",
    panel_legal_aviso: "Aviso legal:",
    panel_legal_panel:
      "La información mostrada en este panel es orientativa y puede requerir validación adicional.",
    panel_copied: "Copiado",
    panel_copy: "Copiar",
    panel_continue: "Continuar",
    panel_search_agent: "Buscar con agente",
    panel_client_data: "Datos del cliente",
    panel_completed_pct: "completado",
    panel_stat_up_to: "Hasta hoy",
    panel_stat_tramites: "Trámites",
    panel_stat_tramites_sub: "1 en curso · 1 pendiente",
    panel_stat_cita_next: "Próxima cita",
    panel_stat_next_appt_sub: "Renovación TIE · 10:30",
    panel_stat_docs: "Documentos",
    panel_action_cita: "Buscar cita",
    panel_action_cita_sub: "Encuentra disponibilidad",
    panel_action_reg: "Regularización",
    panel_action_reg_sub: "Revisa tu elegibilidad",
    panel_action_upload: "Subir documentos",
    panel_action_upload_sub: "Envía archivos",
    panel_action_ia: "Asistente IA",
    panel_action_ia_sub: "Consulta rápida",
    panel_tramite_curso: "En curso",
    panel_tramite_pending: "Pendiente",
    panel_tramite_s1: "Inicio",
    panel_tramite_s2: "Documentos",
    panel_tramite_s3: "Revisión",
    panel_tramite_s4: "Final",
    panel_nav_resumen: "Resumen",
    panel_nav_tramites: "Trámites",
    panel_nav_citas: "Citas",
    panel_nav_docs: "Docs",
    panel_notif_btn: "Notificaciones",
    panel_notif_close: "Cerrar",
    panel_cita_proxima: "Próxima",
    panel_cita_done: "Completada",
    panel_wa_confirmed: "Confirmada por WhatsApp",
    panel_new_appt_agent: "Buscar nueva cita con agente",
    panel_upload_new: "Subir nuevo documento",
    panel_full_name: "Nombre completo",
    panel_nationality: "Nacionalidad",
    panel_birthdate: "Fecha de nacimiento",

    // DOCUMENTOS
    docs_required_title: "Documentos requeridos",
    doc_uploaded: "Subido",
    doc_pending: "Pendiente",
    doc_replace: "Reemplazar",
    doc_upload: "Subir",
    my_uploaded_docs: "Mis documentos subidos",
    loading: "Cargando...",
    documents_count: "documentos",
    loading_documents: "Cargando documentos",
    no_documents_uploaded: "Todavía no has subido documentos",
    doc_passport: "Pasaporte",
    doc_dni_nie: "DNI / NIE",
    doc_empadronamiento: "Empadronamiento",
    doc_pruebas_espana: "Pruebas de estancia en España",
    doc_fotografias: "Fotografías",
    doc_formulario_oficial: "Formulario oficial",
    doc_tasa_pagada: "Tasa pagada",
    doc_required: "Obligatorio",
    doc_if_available: "Si disponible",
    doc_important: "Importante",
    doc_very_important: "Muy importante",
    doc_pending_fill: "Pendiente de rellenar",
    proofs_complete_counter: "✔ {total}/{min} pruebas completas",
    proofs_counter: "{total}/{min} pruebas",

    // APPOINTMENTS LABELS
    appointment_tie_renewal: "Renovación TIE",
    appointment_empadronamiento: "Empadronamiento",
    appointment_nie_assignment: "Asignación NIE",
    appointment_place_madrid_center: "Comisaría Madrid Centro",
    appointment_place_madrid_townhall: "Ayuntamiento de Madrid",
    appointment_place_madrid_north: "Oficina Madrid Norte",

    // PROCEDURES
    procedure_tie_renewal: "Renovación TIE",
    procedure_arraigo_social: "Arraigo Social",

    // REGULARIZACIÓN
    reg_title: "Regularización 2026",
    reg_sub: "Comprueba si puedes regularizarte y prepara tu expediente",
    reg_new: "Nuevo",
    reg_activar: "Activar plan",
    reg_alert_text:
      "Consulta la información y revisa si cumples los requisitos.",

    // LEGAL / FOOTER
    legal_title: "Aviso legal",
    legal_text:
      "La información proporcionada por esta plataforma es orientativa y no sustituye el asesoramiento jurídico profesional individualizado.",
    legal_accept: "He leído y acepto",
    legal_label: "Aviso legal",
    legal_body:
      "La información mostrada es orientativa y no sustituye asesoramiento jurídico profesional.",
    footer_legal: "Aviso legal",
    footer_privacy: "Privacidad",
    footer_cookies: "Cookies",

    // PAYMENT
    secure_payment_methods: "Pago seguro · Métodos aceptados",
    ssl_payment_text:
      "Pagos procesados con cifrado SSL 256-bit · PCI DSS Compliant",

    // MISC
    verified: "Verificado",
    in_review: "En revisión",
    rejected: "Rechazado",
    expired: "Caducado",
    pending: "Pendiente",
    apt: "Apto",
    not_apt: "No apto",
    result: "Resultado",
    reviewed_by: "Revisado por",
    reviewed_on: "Revisado el",
    expires_on: "Caduca el",
    note: "Nota",
    detected_as: "Detectado como",
    type: "Tipo",
    status: "Estado",
    system: "Sistema",
    reviewed: "Revisado",
    form_created_title: "Formulario creado",
    form_created_desc: "Formulario preparado automáticamente con los datos del perfil.",
    form_create_error_title: "Error al crear formulario",
    form_create_error_desc: "No se pudo crear el formulario automático",
    access_error_title: "Error de acceso",
    access_error_desc: "No se pudo iniciar sesión con Google",
    error_loading_documents_title: "Error al cargar documentos",
    error_loading_documents_desc: "No se pudieron cargar los documentos",
    document_uploaded_title: "Documento subido",
    document_uploaded_desc: "Documento recibido correctamente. Ahora está en revisión.",
    error_upload_title: "Error al subir",
    error_upload_desc: "No se pudo subir el documento",
    error_download_title: "Error al descargar",
    error_download_desc: "No se pudo descargar el documento",
    google_login_error: "Error al iniciar sesión con Google",
    google_login_failed: "No se pudo iniciar sesión con Google",
    secure_payment: "Pago seguro",
    online: "En línea",
    close: "Cerrar",
    create_auto_form: "Crear formulario automático",
    automatic_forms: "Formularios automáticos",
    created: "creados",
    no_automatic_forms: "Aún no has creado formularios automáticos.",
    passport: "Pasaporte",
    panel_phone: "Tel.",
    panel_email: "Email",
    form_created: "Formulario creado",
    no_notifications: "No hay notificaciones todavía",
    per_month: "mes",
  },

  en: {
    nav_inicio: "Home",
    nav_panel: "Dashboard",
    nav_citas: "Appointments",
    nav_reg: "Regularization 2026",
    nav_login: "Log in",
    nav_logout: "Log out",
    nav_documentos: "Documents",
    nav_contacto: "Contact",
    nav_idioma: "Language",

    hero_badge: "Immigration AI Agent — 100% legal and secure",
    hero_title_1: "Find out if you can",
    hero_title_2: "regularize your status in Spain",
    hero_sub:
      "Our AI agent analyzes your situation, reviews your documents, and guides you step by step in a clear, fast, and secure way.",
    hero_btn1: "Start now",
    hero_btn_citas: "Find appointments",
    hero_btn2: "View my dashboard",
    hero_trust: "Thousands of people already use GestoriaCitaIA",

    feat1: "Fast analysis",
    feat2: "Document review",
    feat3: "PDF preparation",
    feat4: "Step-by-step assistance",

    agent_mo_role: "Immigration Specialist",
    agent_sara_role: "Appointment Search · 24/7",

    landing_video_text: "How GestoriaCitaIA works in 2 minutes",

    plans_title: "Our plans",
    plans_sub: "Choose the option that best fits your situation",
    plan_popular: "Most popular",
    plan_btn: "Start",
    plan_free_btn: "Try for free",

    plan_free_name: "Free",
    plan_cita_name: "Appointments Plan",
    plan_reg_name: "Regularization Plan",
    plan_std_name: "Standard Plan",

    plan_free_f1: "Initial consultation with AI agent",
    plan_free_f2: "Basic guidance",
    plan_free_f3: "General information",
    plan_free_f4: "Limited access",

    plan_cita_f1: "Appointment search",
    plan_cita_f2: "Availability tracking",
    plan_cita_f3: "Priority alerts",
    plan_cita_f4: "24/7 assistant",
    plan_cita_f5: "Step-by-step help",
    plan_cita_f6: "Management support",

    plan_reg_f1: "Regularization analysis",
    plan_reg_f2: "Document review",
    plan_reg_f3: "Requirements check",
    plan_reg_f4: "File preparation",
    plan_reg_f5: "Personalized assistance",

    plan_std_f1: "Everything in Appointments Plan",
    plan_std_f2: "Everything in Regularization Plan",
    plan_std_f3: "Upload and review documents",
    plan_std_f4: "Form preparation",
    plan_std_f5: "Case tracking",
    plan_std_f6: "Important notifications",
    plan_std_f7: "Full support",

    tramites_title: "Available procedures",
    tramites_sub: "We help you with the most important immigration procedures",
    tr_tie: "TIE renewal",
    tr_visado_nac: "National visa",
    tr_nie: "NIE",
    tr_empadron: "Registration certificate",
    tr_trabajo: "Work permit",
    tr_familiar: "Family reunification",
    tr_estudiante: "Student stay",
    tr_arraigo: "Settlement permit",
    tr_conducir: "Driving license exchange",
    tr_larga: "Long-term residence",
    tr_regreso: "Return authorization",
    tr_ue: "EU certificate",

    common_loading: "Loading...",
    common_error: "An error occurred",
    common_success: "Operation completed successfully",
    common_cancel: "Cancel",
    common_save: "Save",
    common_close: "Close",
    common_continue: "Continue",
    common_back: "Back",
    common_next: "Next",
    common_send: "Send",
    common_yes: "Yes",
    common_no: "No",
    common_required: "Required",
    common_optional: "Optional",
    common_select: "Select",
    common_search: "Search",
    common_download: "Download",
    common_upload: "Upload",
    common_delete: "Delete",
    common_edit: "Edit",
    common_view: "View",
    common_free: "Free",
    common_paid: "Paid",

    panel_title: "Your dashboard",
    panel_subtitle: "Manage your process from one place",
    panel_welcome: "Welcome",
    panel_cases: "Your cases",
    panel_documents: "Your documents",
    panel_notifications: "Notifications",
    panel_profile: "Profile",
    panel_no_data: "No data available yet",
    panel_header: "Dashboard",
    panel_tab_docs: "Documents",
    panel_tab_profile: "Profile",
    panel_tab_notifications: "Notifications",
    panel_plan_active: "Active plan",
    panel_tab_resumen: "Summary",
    panel_tab_tramites: "Procedures",
    panel_tab_citas: "Appointments",
    panel_active: "Active",
    panel_plan_used: "Plan used",
    panel_procedures: "Procedures",
    panel_next_invoice: "Next invoice",
    panel_manage_plan: "Manage plan",
    panel_new_appt: "New appointment",
    panel_tramites_curso: "Active procedures",
    panel_quick_actions: "Quick actions",
    panel_referral_title: "Invite and earn",
    panel_referral_reward: "Discount",
    panel_referral_desc: "Share your code and get rewards.",
    panel_referrals_bought: "Completed referrals",
    panel_referral_left: "You still need",
    panel_referral_more: "more to get your reward",
    panel_legal_aviso: "Legal notice:",
    panel_legal_panel:
      "The information shown in this dashboard is for guidance only and may require additional validation.",
    panel_copied: "Copied",
    panel_copy: "Copy",
    panel_continue: "Continue",
    panel_search_agent: "Search with agent",
    panel_client_data: "Client data",
    panel_completed_pct: "completed",
    panel_stat_up_to: "Up to today",
    panel_stat_tramites: "Procedures",
    panel_stat_tramites_sub: "1 active · 1 pending",
    panel_stat_cita_next: "Next appointment",
    panel_stat_next_appt_sub: "TIE renewal · 10:30",
    panel_stat_docs: "Documents",
    panel_action_cita: "Find appointment",
    panel_action_cita_sub: "Find availability",
    panel_action_reg: "Regularization",
    panel_action_reg_sub: "Check your eligibility",
    panel_action_upload: "Upload documents",
    panel_action_upload_sub: "Send files",
    panel_action_ia: "AI assistant",
    panel_action_ia_sub: "Quick help",
    panel_tramite_curso: "In progress",
    panel_tramite_pending: "Pending",
    panel_tramite_s1: "Start",
    panel_tramite_s2: "Documents",
    panel_tramite_s3: "Review",
    panel_tramite_s4: "Finish",
    panel_nav_resumen: "Summary",
    panel_nav_tramites: "Procedures",
    panel_nav_citas: "Appointments",
    panel_nav_docs: "Docs",
    panel_notif_btn: "Notifications",
    panel_notif_close: "Close",
    panel_cita_proxima: "Upcoming",
    panel_cita_done: "Completed",
    panel_wa_confirmed: "Confirmed by WhatsApp",
    panel_new_appt_agent: "Find new appointment with agent",
    panel_upload_new: "Upload new document",
    panel_full_name: "Full name",
    panel_nationality: "Nationality",
    panel_birthdate: "Birth date",

    docs_required_title: "Required documents",
    doc_uploaded: "Uploaded",
    doc_pending: "Pending",
    doc_replace: "Replace",
    doc_upload: "Upload",
    my_uploaded_docs: "My uploaded documents",
    loading: "Loading...",
    documents_count: "documents",
    loading_documents: "Loading documents",
    no_documents_uploaded: "You have not uploaded documents yet",
    doc_passport: "Passport",
    doc_dni_nie: "ID / NIE",
    doc_empadronamiento: "Registration certificate",
    doc_pruebas_espana: "Proof of stay in Spain",
    doc_fotografias: "Photographs",
    doc_formulario_oficial: "Official form",
    doc_tasa_pagada: "Paid fee",
    doc_required: "Required",
    doc_if_available: "If available",
    doc_important: "Important",
    doc_very_important: "Very important",
    doc_pending_fill: "Pending completion",
    proofs_complete_counter: "✔ {total}/{min} complete proofs",
    proofs_counter: "{total}/{min} proofs",

    appointment_tie_renewal: "TIE renewal",
    appointment_empadronamiento: "Registration certificate",
    appointment_nie_assignment: "NIE assignment",
    appointment_place_madrid_center: "Madrid Central Police Office",
    appointment_place_madrid_townhall: "Madrid City Hall",
    appointment_place_madrid_north: "Madrid North Office",

    procedure_tie_renewal: "TIE renewal",
    procedure_arraigo_social: "Social settlement",

    reg_title: "Regularization 2026",
    reg_sub: "Check if you can regularize your status and prepare your file",
    reg_new: "New",
    reg_activar: "Activate plan",
    reg_alert_text: "Review the information and check whether you meet the requirements.",

    legal_title: "Legal notice",
    legal_text:
      "The information provided by this platform is for guidance purposes only and does not replace individualized professional legal advice.",
    legal_accept: "I have read and accept",
    legal_label: "Legal notice",
    legal_body:
      "The information shown is for guidance only and does not replace professional legal advice.",
    footer_legal: "Legal notice",
    footer_privacy: "Privacy",
    footer_cookies: "Cookies",

    secure_payment_methods: "Secure payment · Accepted methods",
    ssl_payment_text:
      "Payments processed with 256-bit SSL encryption · PCI DSS Compliant",

    verified: "Verified",
    in_review: "In review",
    rejected: "Rejected",
    expired: "Expired",
    pending: "Pending",
    apt: "Valid",
    not_apt: "Not valid",
    result: "Result",
    reviewed_by: "Reviewed by",
    reviewed_on: "Reviewed on",
    expires_on: "Expires on",
    note: "Note",
    detected_as: "Detected as",
    type: "Type",
    status: "Status",
    system: "System",
    reviewed: "Reviewed",
    form_created_title: "Form created",
    form_created_desc: "Form prepared automatically with profile data.",
    form_create_error_title: "Error creating form",
    form_create_error_desc: "The automatic form could not be created",
    access_error_title: "Access error",
    access_error_desc: "Could not sign in with Google",
    error_loading_documents_title: "Error loading documents",
    error_loading_documents_desc: "Documents could not be loaded",
    document_uploaded_title: "Document uploaded",
    document_uploaded_desc: "Document received correctly. It is now under review.",
    error_upload_title: "Upload error",
    error_upload_desc: "Could not upload the document",
    error_download_title: "Download error",
    error_download_desc: "Could not download the document",
    google_login_error: "Error signing in with Google",
    google_login_failed: "Could not sign in with Google",
    secure_payment: "Secure payment",
    online: "Online",
    close: "Close",
    create_auto_form: "Create automatic form",
    automatic_forms: "Automatic forms",
    created: "created",
    no_automatic_forms: "You have not created automatic forms yet.",
    passport: "Passport",
    panel_phone: "Phone",
    panel_email: "Email",
    form_created: "Form created",
    no_notifications: "There are no notifications yet",
    per_month: "month",
  },

  darija: {
    nav_inicio: "الرئيسية",
    nav_panel: "البانيل",
    nav_citas: "المواعيد",
    nav_reg: "التسوية 2026",
    nav_login: "دخول",
    nav_logout: "خروج",
    nav_documentos: "الوثائق",
    nav_contacto: "تواصل",
    nav_idioma: "اللغة",

    hero_badge: "مساعد الذكاء الاصطناعي ديال الهجرة — قانوني وآمن 100%",
    hero_title_1: "عرف واش تقدر",
    hero_title_2: "تسوي الوضعية ديالك فإسبانيا",
    hero_sub:
      "المساعد ديالنا كايحلل الحالة ديالك، كايشوف الوثائق ديالك، وكايوجهك مرحلة بمرحلة بطريقة واضحة وسريعة وآمنة.",
    hero_btn1: "بدا دابا",
    hero_btn_citas: "المواعيد",
    hero_btn2: "شوف البانيل ديالي",
    hero_trust: "آلاف الناس كايستعملو GestoriaCitaIA",

    feat1: "تحليل سريع",
    feat2: "مراجعة الوثائق",
    feat3: "تحضير PDF",
    feat4: "مساعدة مرحلة بمرحلة",

    agent_mo_role: "متخصص فالهجرة",
    agent_sara_role: "البحث عن المواعيد · 24/7",

    landing_video_text: "كيفاش كتخدم GestoriaCitaIA فـ جوج دقايق",

    plans_title: "الخطط ديالنا",
    plans_sub: "اختار الخطة اللي كتناسب الحالة ديالك",
    plan_popular: "الأكثر شعبية",
    plan_btn: "بدا",
    plan_free_btn: "جرب مجانا",

    plan_free_name: "مجاني",
    plan_cita_name: "خطة المواعيد",
    plan_reg_name: "خطة التسوية",
    plan_std_name: "الخطة العادية",

    plan_free_f1: "استشارة أولية مع وكيل الذكاء الاصطناعي",
    plan_free_f2: "توجيه أساسي",
    plan_free_f3: "معلومات عامة",
    plan_free_f4: "ولوج محدود",

    plan_cita_f1: "البحث عن المواعيد",
    plan_cita_f2: "تتبع التوفر",
    plan_cita_f3: "إشعارات أولوية",
    plan_cita_f4: "مساعد 24/7",
    plan_cita_f5: "مساعدة خطوة بخطوة",
    plan_cita_f6: "دعم فالتسيير",

    plan_reg_f1: "تحليل التسوية",
    plan_reg_f2: "مراجعة الوثائق",
    plan_reg_f3: "التحقق من الشروط",
    plan_reg_f4: "تحضير الملف",
    plan_reg_f5: "مساعدة مخصصة",

    plan_std_f1: "كلشي اللي فخطة المواعيد",
    plan_std_f2: "كلشي اللي فخطة التسوية",
    plan_std_f3: "رفع ومراجعة الوثائق",
    plan_std_f4: "تحضير الاستمارات",
    plan_std_f5: "تتبع الملف",
    plan_std_f6: "إشعارات مهمة",
    plan_std_f7: "دعم كامل",

    tramites_title: "الخدمات المتاحة",
    tramites_sub: "كنعاونوك فأهم خدمات الهجرة والأوراق",
    tr_tie: "تجديد TIE",
    tr_visado_nac: "الفيزا الوطنية",
    tr_nie: "NIE",
    tr_empadron: "السكنى",
    tr_trabajo: "رخصة العمل",
    tr_familiar: "التجمع العائلي",
    tr_estudiante: "الإقامة للدراسة",
    tr_arraigo: "الاستقرار",
    tr_conducir: "تبديل رخصة السياقة",
    tr_larga: "الإقامة الطويلة",
    tr_regreso: "رخصة الرجوع",
    tr_ue: "شهادة الاتحاد الأوروبي",

    common_loading: "جاري التحميل...",
    common_error: "وقع خطأ",
    common_success: "تمت العملية بنجاح",
    common_cancel: "إلغاء",
    common_save: "حفظ",
    common_close: "إغلاق",
    common_continue: "كمل",
    common_back: "رجوع",
    common_next: "التالي",
    common_send: "إرسال",
    common_yes: "نعم",
    common_no: "لا",
    common_required: "إجباري",
    common_optional: "اختياري",
    common_select: "اختار",
    common_search: "بحث",
    common_download: "تحميل",
    common_upload: "رفع",
    common_delete: "حذف",
    common_edit: "تعديل",
    common_view: "شوف",
    common_free: "مجاني",
    common_paid: "بالمقابل",

    panel_title: "البانيل ديالك",
    panel_subtitle: "سير المسار ديالك من بلاصة وحدة",
    panel_welcome: "مرحبا",
    panel_cases: "الملفات ديالك",
    panel_documents: "الوثائق ديالك",
    panel_notifications: "الإشعارات",
    panel_profile: "البروفايل",
    panel_no_data: "ما كاين حتى معطيات دابا",
    panel_header: "البانيل",
    panel_tab_docs: "الوثائق",
    panel_tab_profile: "البروفايل",
    panel_tab_notifications: "الإشعارات",
    panel_plan_active: "الخطة النشيطة",
    panel_tab_resumen: "الخلاصة",
    panel_tab_tramites: "الخدمات",
    panel_tab_citas: "المواعيد",
    panel_active: "نشط",
    panel_plan_used: "الخطة المستعملة",
    panel_procedures: "الخدمات",
    panel_next_invoice: "الفاتورة الجاية",
    panel_manage_plan: "تدبير الخطة",
    panel_new_appt: "موعد جديد",
    panel_tramites_curso: "الخدمات الجارية",
    panel_quick_actions: "إجراءات سريعة",
    panel_referral_title: "جيب صحابك وربح",
    panel_referral_reward: "تخفيض",
    panel_referral_desc: "شارك الكود ديالك وخذ مكافآت.",
    panel_referrals_bought: "الإحالات المكتملة",
    panel_referral_left: "باقي ليك",
    panel_referral_more: "باش تاخد المكافأة",
    panel_legal_aviso: "تنبيه قانوني:",
    panel_legal_panel:
      "المعلومات اللي كتشوف فهاد البانيل غير للتوجيه وقد تحتاج مراجعة إضافية.",
    panel_copied: "تنسخ",
    panel_copy: "نسخ",
    panel_continue: "كمل",
    panel_search_agent: "قلب مع الوكيل",
    panel_client_data: "معطيات الزبون",
    panel_completed_pct: "مكتمل",
    panel_stat_up_to: "حتى لدابا",
    panel_stat_tramites: "الخدمات",
    panel_stat_tramites_sub: "1 خدام · 1 معلق",
    panel_stat_cita_next: "الموعد الجاي",
    panel_stat_next_appt_sub: "تجديد TIE · 10:30",
    panel_stat_docs: "الوثائق",
    panel_action_cita: "قلب على موعد",
    panel_action_cita_sub: "شوف التوفر",
    panel_action_reg: "التسوية",
    panel_action_reg_sub: "شوف واش صالح",
    panel_action_upload: "رفع الوثائق",
    panel_action_upload_sub: "صيفط الملفات",
    panel_action_ia: "مساعد ذكي",
    panel_action_ia_sub: "مساعدة سريعة",
    panel_tramite_curso: "قيد الإنجاز",
    panel_tramite_pending: "معلق",
    panel_tramite_s1: "بداية",
    panel_tramite_s2: "الوثائق",
    panel_tramite_s3: "المراجعة",
    panel_tramite_s4: "النهاية",
    panel_nav_resumen: "الخلاصة",
    panel_nav_tramites: "الخدمات",
    panel_nav_citas: "المواعيد",
    panel_nav_docs: "الوثائق",
    panel_notif_btn: "الإشعارات",
    panel_notif_close: "سد",
    panel_cita_proxima: "قريب",
    panel_cita_done: "مكمل",
    panel_wa_confirmed: "مأكد فالواتساب",
    panel_new_appt_agent: "قلب على موعد جديد مع الوكيل",
    panel_upload_new: "رفع وثيقة جديدة",
    panel_full_name: "الاسم الكامل",
    panel_nationality: "الجنسية",
    panel_birthdate: "تاريخ الازدياد",

    docs_required_title: "الوثائق المطلوبة",
    doc_uploaded: "مرفوع",
    doc_pending: "معلق",
    doc_replace: "بدل",
    doc_upload: "رفع",
    my_uploaded_docs: "الوثائق اللي رفعت",
    loading: "جاري التحميل...",
    documents_count: "وثائق",
    loading_documents: "جاري تحميل الوثائق",
    no_documents_uploaded: "مازال ما رفعتي حتى وثيقة",
    doc_passport: "الباسبور",
    doc_dni_nie: "DNI / NIE",
    doc_empadronamiento: "شهادة السكنى",
    doc_pruebas_espana: "إثباتات الوجود فإسبانيا",
    doc_fotografias: "الصور",
    doc_formulario_oficial: "الاستمارة الرسمية",
    doc_tasa_pagada: "الرسوم المؤداة",
    doc_required: "إجباري",
    doc_if_available: "إلى كان",
    doc_important: "مهم",
    doc_very_important: "مهم بزاف",
    doc_pending_fill: "خاصو يتعمر",
    proofs_complete_counter: "✔ {total}/{min} إثباتات كاملة",
    proofs_counter: "{total}/{min} إثباتات",

    appointment_tie_renewal: "تجديد TIE",
    appointment_empadronamiento: "شهادة السكنى",
    appointment_nie_assignment: "تعيين NIE",
    appointment_place_madrid_center: "كوميساريا مدريد المركز",
    appointment_place_madrid_townhall: "بلدية مدريد",
    appointment_place_madrid_north: "مكتب مدريد الشمال",

    procedure_tie_renewal: "تجديد TIE",
    procedure_arraigo_social: "الاستقرار الاجتماعي",

    reg_title: "التسوية 2026",
    reg_sub: "شوف واش تقدر تسوي الوضعية ديالك وجهز الملف",
    reg_new: "جديد",
    reg_activar: "فعّل الخطة",
    reg_alert_text: "شوف المعلومات وتحقق واش كتوفر فيك الشروط.",

    legal_title: "تنبيه قانوني",
    legal_text:
      "المعلومات اللي كتقدمها هاد المنصة غير للتوجيه وما كتعوضش الاستشارة القانونية المهنية الخاصة بكل حالة.",
    legal_accept: "قريت ووافقت",
    legal_label: "تنبيه قانوني",
    legal_body:
      "المعلومات المعروضة غير للتوجيه وما كتعوضش الاستشارة القانونية المهنية.",
    footer_legal: "تنبيه قانوني",
    footer_privacy: "الخصوصية",
    footer_cookies: "الكوكيز",

    secure_payment_methods: "أداء آمن · وسائل الأداء المقبولة",
    ssl_payment_text: "الأداءات محمية بتشفير SSL 256-bit · PCI DSS Compliant",

    verified: "متحقق",
    in_review: "قيد المراجعة",
    rejected: "مرفوض",
    expired: "منتهي",
    pending: "معلق",
    apt: "صالح",
    not_apt: "غير صالح",
    result: "النتيجة",
    reviewed_by: "راجعو",
    reviewed_on: "تراجع فـ",
    expires_on: "كيسالي فـ",
    note: "ملاحظة",
    detected_as: "تكتشف على أنه",
    type: "النوع",
    status: "الحالة",
    system: "النظام",
    reviewed: "مراجع",
    form_created_title: "تخلق الفورمولير",
    form_created_desc: "توجد الفورمولير أوتوماتيكيا بمعطيات البروفايل.",
    form_create_error_title: "خطأ فخلق الفورمولير",
    form_create_error_desc: "ما قدرناش نخلقو الفورمولير الأوتوماتيكي",
    access_error_title: "خطأ فالولوج",
    access_error_desc: "ما قدرناش ندخلو بجوجل",
    error_loading_documents_title: "خطأ فتحميل الوثائق",
    error_loading_documents_desc: "ما قدرناش نحملو الوثائق",
    document_uploaded_title: "ترفعات الوثيقة",
    document_uploaded_desc: "توصلنا بالوثيقة ودابا غادي تتراجع.",
    error_upload_title: "خطأ فالرفع",
    error_upload_desc: "ما قدرناش نرفعو الوثيقة",
    error_download_title: "خطأ فالتحميل",
    error_download_desc: "ما قدرناش نحملو الوثيقة",
    google_login_error: "خطأ فالدخول بجوجل",
    google_login_failed: "ما قدرناش ندخلو بجوجل",
    secure_payment: "أداء آمن",
    online: "متصل",
    close: "سد",
    create_auto_form: "صاوب فورمولير أوتوماتيكي",
    automatic_forms: "الفورموليرات الأوتوماتيكية",
    created: "متصاوبين",
    no_automatic_forms: "مازال ما صاوبتي حتى فورمولير أوتوماتيكي.",
    passport: "الباسبور",
    panel_phone: "الهاتف",
    panel_email: "الإيميل",
    form_created: "تخلق الفورمولير",
    no_notifications: "ما كايناش إشعارات دابا",
    per_month: "شهر",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("es");

  useEffect(() => {
    const savedLang = localStorage.getItem(STORAGE_KEY) as Lang | null;
    if (savedLang === "es" || savedLang === "en" || savedLang === "darija") {
      setLangState(savedLang);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);

    const isRTL = lang === "darija";
    document.documentElement.lang = lang === "darija" ? "ar" : lang;
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.body.dir = isRTL ? "rtl" : "ltr";
  }, [lang]);

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] ?? translations.es?.[key] ?? key;
  };

  const value = useMemo(
    () => ({
      lang,
      setLang,
      t,
      isRTL: lang === "darija",
      translations: translations[lang] || {},
    }),
    [lang]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLang must be used within a LanguageProvider");
  }

  return context;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }

  return context;
}
